"""Search helper for the HR chatbot.

This file is a placeholder for reusable query and search logic.
"""

# Add search helper functions here as the project grows.

import os
from typing import List, Any

from openai import OpenAI
from qdrant_client import QdrantClient

from embeddings import create_embedding

from dotenv import load_dotenv
from openai import OpenAI


load_dotenv()

COLLECTION_NAME = "hr_docs"

NOT_FOUND_MESSAGE = (
    "Sorry, I couldn't find an answer to your question in the uploaded documents. "
    "Please try rephrasing your question or upload additional documents if needed."
)

ai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def create_qdrant_client(path: str = "./qdrant_data") -> QdrantClient:
    return QdrantClient(path=path)


def search_documents(
    client: QdrantClient,
    question: str,
    limit: int = 10,
) -> List[Any]:
    
    """Search the Qdrant collection for document chunks relevant to a question.

    This function converts the user's natural language question into an
    embedding vector and performs a similarity search against the
    configured Qdrant collection. The most relevant document chunks
    are returned based on vector similarity.

    Args:
        client:
            An initialized Qdrant client connected to the database.

        question:
            The user's natural language query.

            Example:
                "How many annual leave days do employees get?"

        limit:
            Maximum number of matching document chunks to retrieve.

            Default:
                10

    Returns:
        A list of Qdrant scored points ordered by relevance.

        Each point contains:

        - score: Similarity score.
        - payload["text"]: Retrieved document chunk.
        - payload["file"]: Source document name.
        - payload["source_id"]: Unique source identifier.

    Example:
        Input:

            question = "What is the sick leave policy?"

        Output:

            [
                {
                    "score": 0.92,
                    "payload": {
                        "text": "Employees are entitled to 10 sick leave days.",
                        "file": "leave_policy.pdf",
                        "source_id": 0
                    }
                }
            ]
    """

    query_vector = create_embedding(question)

    results = client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector,
        limit=limit,
    )

    return results.points


def build_context(points: List[Any]) -> str:

    """Build a single context string from retrieved Qdrant search results.

    This function extracts the `text` field from each point's payload
    and combines all non-empty text chunks into one string separated
    by blank lines. The resulting context is passed to the LLM so it
    can answer the user's question using the retrieved documents.

    Args:
        points:
            List of Qdrant search result points. Each point is expected
            to contain a payload with a `text` key.

    Returns:
        A single string containing all retrieved text chunks separated
        by two newline characters (`\\n\\n`).

    Example:
        Input payloads:

        [
            {"text": "Employees receive 20 annual leave days."},
            {"text": "Sick leave is 10 days."}
        ]

        Output:

        "Employees receive 20 annual leave days.\n\n"
        "Sick leave is 10 days."
    """

    contexts = []

    for point in points:

        text = point.payload.get("text", "")

        if text:
            contexts.append(text)

    return "\n\n".join(contexts)


def answer_question(question: str, context: str) -> str:

    """Generate an answer to a user's question using retrieved document context.

    This function sends the user's question and the relevant document
    context to the OpenAI Chat Completion API. The model is instructed
    to answer ONLY from the provided context and not rely on external
    knowledge.

    If the required information is not present in the retrieved
    documents, the model is instructed to return:

        "I could not find this information in the uploaded documents."

    Args:
        question:
            The user's natural language question.

            Example:
                "How many annual leave days do employees get?"

        context:
            Combined text retrieved from Qdrant search results.
            This typically contains one or more document chunks that
            are relevant to the user's question.

            Example:
                "Employees receive 20 annual leave days.\n\n"
                "Sick leave is 10 days."

    Returns:
        A natural language answer generated by the OpenAI model.

        Example:
            "Employees are entitled to 20 annual leave days."

    Raises:
        openai.APIError:
            If the OpenAI API request fails.

        openai.RateLimitError:
            If the API rate limit is exceeded.

        openai.AuthenticationError:
            If the API key is invalid.
    """
    from llm.prompt_builder import (DOCUMENT_SYSTEM_PROMPT,build_document_prompt)
    
    prompt = build_document_prompt(
        question,
        context
    )

    response = ai_client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=[

            {
                "role": "system",

                "content": DOCUMENT_SYSTEM_PROMPT
                # f"""
                # You are an intelligent document assistant.

                # Answer ONLY from the provided context.

                # Rules:

                # 1. Use information only from the documents.
                # 2. Combine information from multiple chunks if needed.
                # 3. Give concise and accurate answers.
                # 4. If the answer is not found, say:

                # "{NOT_FOUND_MESSAGE}"
                # """
            },

            {
                "role": "user",

                "content": prompt

                # f"""
                # Context:

                # {context}


                # Question:

                # {question}
                # """
            }

        ]
    )

    return response.choices[0].message.content


def print_sources(points: List[Any]):

    """Print the source document names used to answer the question.

    This function extracts the `file` field from each Qdrant point's
    payload and prints unique document names. A set is used to avoid
    displaying duplicate filenames when multiple chunks come from the
    same document.

    Args:
        points:
            List of Qdrant search result points. Each point is expected
            to contain a payload with a `file` key representing the
            source document name.

    Returns:
        None

    Example:
        Input:

            points = [
                {
                    "payload": {
                        "file": "leave_policy.pdf"
                    }
                },

                {
                    "payload": {
                        "file": "leave_policy.pdf"
                    }
                },

                {
                    "payload": {
                        "file": "employee_handbook.pdf"
                    }
                }
            ]

        Output:

            Sources:

            - leave_policy.pdf
            - employee_handbook.pdf
    """

    print("\nSources:")

    seen = set()

    for point in points:

        filename = point.payload.get("file")

        if filename and filename not in seen:

            seen.add(filename)

            print(f"- {filename}")


def answer_document_question(question: str):

    client = create_qdrant_client()

    try:

        points = search_documents(
            client,
            question,
            limit=10
        )

        if not points:
            return NOT_FOUND_MESSAGE, []

        context = build_context(points)

        answer = answer_question(
            question,
            context
        )

        sources = get_sources(points)

        return answer, sources

    finally:

        client.close()


def get_sources(points: List[Any]) -> list[str]:

    sources = []

    seen = set()

    for point in points:

        filename = point.payload.get("file")

        if filename and filename not in seen:

            seen.add(filename)

            sources.append(filename)

    return sources

def retrieve_document_context(question):

    client = create_qdrant_client()

    points = search_documents(
        client,
        question
    )

    context = build_context(points)

    sources = get_sources(points)

    return context, sources


def main():

    client = create_qdrant_client()

    while True:

        question = input("\nAsk a question (or type exit): ").strip()

        if question.lower() == "exit":
            break

        if not question:
            continue

        points = search_documents(
            client,
            question,
            limit=10
        )

        if not points:

            print("No relevant documents found.")

            continue

        context = build_context(points)

        answer = answer_question(question, context)

        print("\nAnswer:\n")
        print(answer)

        if answer.strip() != NOT_FOUND_MESSAGE:
            print_sources(points)

    client.close()


if __name__ == "__main__":
    main()
